#Name of the workflow
name: Java CI with Maven new workflow

on:
  #schedule:
   # - cron: "2 * * * *"
  #Trigger that allows manually trigger a GitHub Action
  #push:
  pull_request:
     types:
         - opened
     branches:
         - master
  #workflow_dispatch:
  
jobs:
  #Name of the job
  build:
    #Job will execute on fresh VM hosted by GitHub
    runs-on: ubuntu-latest
   
    #Individual tasks to run commands in a job
    steps:
    
    #Checks-out your repository under $GITHUB_WORKSPACE,so our workflow can access it
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

   
      
    - name: Build with Maven
      run: |
        mvn clean install 
        mvn clean verify
        ls -l target/*
      

   
 
